
name: Run app.js with PM2

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Change directory to api
        run: cd api

      - name: Install dependencies
        run: npm install

      - name: Install PM2
        run: npm install pm2 -g

      - name: Start app.js with PM2
        run: pm2 start app.js

